config/routes.rb
Rails.application.routes.draw do
  resources :items do
    post 'mark-as-done' => 'items#mark_as_done'
  end

  root to: 'items#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
  validates :title, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      flash[:notice] = "#{@item.title} was created successfully."

      redirect_to item_path(@item)
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])

    if @item.update_attributes(item_params)
      flash[:notice] = "#{@item.title} was updated successfully."

      redirect_to item_path(@item)
    else
      render :edit
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def destroy
    @item = Item.find(params[:id])

    @item.destroy!

    redirect_to items_path
  end

  def mark_as_done
    @item = Item.find(params[:item_id])

    @item.completed_at = Time.now
    @item.save!

    flash[:notice] = "#{@item.title} was marked as done."

    redirect_to :back
  end

  private

  def item_params
    params.require(:item).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.haml
= form_for item do |f|
  - if item.errors.any?
    .errors
      = item.errors.full_messages.to_sentence
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body

  = f.submit
  
  - if item.new_record?
    = link_to 'Cancel', items_path
  - else
    = link_to 'Cancel', item_path(item)

app/views/items/edit.haml
%h1
  Edit
  = @item.title

= render 'form', item: @item

app/views/items/index.haml
%h1
  Items

%a{ href: new_item_path }
  New Item

%hr

%table
  %thead
    %tr
      %th
        Title
      %th
        Completed At

  %tbody
    - @items.each do |item|
      %tr
        %td
          %a{ href: item_path(item) }
            = item.title
        %td
          = item.completed_at

app/views/items/new.haml
%h1
  New Item

= render 'form', item: @item

app/views/items/show.haml
%h1
  = @item.title

- if @item.completed_at.present?
  %h4
    This item was competed at
    = @item.completed_at

%a{href: items_path}
  Back to list

&nbsp;

%a{href: edit_item_path(@item)}
  Edit

&nbsp;

= link_to 'Delete', item_path(@item), method: :delete, data: { confirm: 'Are you sure?' }

- unless @item.completed_at.present?
  = link_to 'Mark As Done', item_mark_as_done_path(@item), method: :post

.item-body
  = @item.body

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogTodoWeatherApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:notice].present? %>
  <div id="notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<%= yield %>

</body>
</html>